version: '2.0'
services:
  meekasa-ui:
    image: rmkasendwa/sliding-tiles
    container_name: sliding-tiles
    environment:
      - RESOLVER_IP=127.0.0.11
      - BACKEND_URL=http://127.0.0.1:8083
    restart: always
